# Generated by Django 3.2.7 on 2021-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_renterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
