# Generated by Django 3.2.7 on 2021-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rentertimings_timing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renterspots',
            name='spots_available',
            field=models.CharField(max_length=3),
        ),
    ]
