# Generated by Django 3.2.7 on 2021-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_rentermodel_renter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentermodel',
            name='renter_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
